export const apartmentData = [
    {
        id: '101',
        photo_1: 'https://i.ibb.co/VY1tXfg/Rectangle-394.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment Three',
        location: 'Rangs Malancha, Dhaka',
        bed: 3,
        bath: 3,
        price: 25000,
        details:
            '3000 sq ft. 3 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-6A',
                houseNo: '68',
                street: 'Rangs Malancha',
                city: 'Dhaka',
            },
            flatSize: 3000,
            floor: {
                facing: 'south',
                floorNumber: 'A5 (5th floor)',
                totalFloor: 6,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '25000',
            negotiable: true,
            ServiceCharge: '8000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
    {
        id: '102',
        photo_1: 'https://i.ibb.co/q5vdBFm/Rectangle-396.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment Two',
        location: 'Lalmatia, Dhaka',
        bed: 4,
        bath: 3,
        price: 30000,
        details:
            '3600 sq ft. 4 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-6A',
                houseNo: '68',
                street: 'Lalmatia',
                city: 'Dhaka',
            },
            flatSize: 3600,
            floor: {
                facing: 'south',
                floorNumber: 'B3 (3rd floor)',
                totalFloor: 8,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '30000',
            negotiable: true,
            ServiceCharge: '10000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
    {
        id: '103',
        photo_1: 'https://i.ibb.co/dDH80DP/Rectangle-398.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment Four',
        location: 'Dhanmondi, Dhaka',
        bed: 3,
        bath: 2,
        price: 25000,
        details:
            '3000 sq ft. 3 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-6A',
                houseNo: '68',
                street: 'Dhanmondi',
                city: 'Dhaka',
            },
            flatSize: 3000,
            floor: {
                facing: 'south',
                floorNumber: 'C5 (5th floor)',
                totalFloor: 6,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '25000',
            negotiable: true,
            ServiceCharge: '5000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
    {
        id: '104',
        photo_1: 'https://i.ibb.co/z504Q7J/Rectangle-404.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment One',
        location: 'Banani, Dhaka',
        bed: 4,
        bath: 4,
        price: 35000,
        details:
            '4000 sq ft. 4 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-6A',
                houseNo: '8',
                street: 'Banani',
                city: 'Dhaka',
            },
            flatSize: 4000,
            floor: {
                facing: 'west',
                floorNumber: 'B2 (2nd floor)',
                totalFloor: 10,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '35000',
            negotiable: true,
            ServiceCharge: '10000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
    {
        id: '105',
        photo_1: 'https://i.ibb.co/KDSmzPq/Rectangle-405.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment Five',
        location: 'Mirpur-2, Dhaka',
        bed: 3,
        bath: 3,
        price: 25000,
        details:
            '3000 sq ft. 3 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-2',
                houseNo: '68',
                street: 'Mirpur-2',
                city: 'Dhaka',
            },
            flatSize: 3000,
            floor: {
                facing: 'East',
                floorNumber: 'A5 (5th floor)',
                totalFloor: 7,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '25000',
            negotiable: true,
            ServiceCharge: '5000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
    {
        id: '106',
        photo_1: 'https://i.ibb.co/z504Q7J/Rectangle-404.png',
        photo_2: 'https://i.ibb.co/TwqDQwV/Rectangle-407.png',
        photo_3: 'https://i.ibb.co/qRtKJs8/Rectangle-408.png',
        photo_4: 'https://i.ibb.co/122kXvC/Rectangle-409.png',
        photo_5: 'https://i.ibb.co/w6YVXnJ/Rectangle-410.png',
        name: 'Family Apartment Three',
        location: 'Gulshan-1, Dhaka',
        bed: 4,
        bath: 4,
        price: 40000,
        details:
            '4200 sq ft. 4 bedrooms, Semi-Furnished, Luxurious, South Facing Apartment for Rent',
        propertyDetails: {
            address: {
                road: 'Road-1',
                houseNo: '70',
                street: 'Police plaza',
                city: 'Dhaka',
            },
            flatSize: 4200,
            floor: {
                facing: 'South',
                floorNumber: 'A5 (5th floor)',
                totalFloor: 8,
            },
            facilities: '1 Modern Lift, All Modern Amenities',
            additionalFacilities: {
                number1: 'Electricity with full generator',
                number2: 'Central gas geyser',
                number3: 'Car parking',
                number4: 'Community conference hall',
                number5: 'Roof top garden',
            },
        },
        pricing: {
            rentPerMonth: '40000',
            negotiable: true,
            ServiceCharge: '10000',
            securityDeposit: 3,
            flatReleasePolicy: 3,
        },
    },
];
